### ISSUE TITLE
Pre-built binary for Windows

### ISSUE THREAD

**Issue by mardukbp** [yoshihitoh/ut-cli#49]
Even though Windows does not belong to the UNIX family, it is useful to have a cross-platform command line tool to generate timestamps. Thank you for writing it!

**Comment by yoshihitoh** [comment]
@mardukbp  Thank you for your feedback!
Okay, I'll add the prebuilt binary for windows this weekend!

**Comment by yoshihitoh** [comment]
@mardukbp I added prebuilt binaries for Windows at the release page.
https://github.com/yoshihitoh/ut-cli/releases/tag/0.1.7

Would you please try these binaries?
I tried them on macOS using Wine5, and seem to be working well.

**Comment by mardukbp** [comment]
Thanks a lot @yoshihitoh! I tried both the GNU build and the MSVC build. `ut g | ut p` works, but issue #50 persists.

**Comment by yoshihitoh** [comment]
Thank you for testing!
I'll fix the issue on issue #50 later :)
